services:
  - type: web
    name: deets
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    envVars:
      - key: PYTHONUNBUFFERED
        value: true
